[project]
name = "chaotic-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.1.1",
    "uvicorn[standard]>=0.37.0",
]
